### ISSUE TITLE
-t option not available

### ISSUE THREAD

**Issue by musabmasood** [probot/smee#108]
-t option is not available in the latest smee-client even though it shows in the codebase. 

I am therefore unable to forward the request to anyother URL than localhost

**Comment by iamdanfox** [comment]
I'd also love to use the `-t` option because my server happens to serve traffic over HTTPS!

It seems like the functionality was landed just last month (https://github.com/probot/smee/pull/83), but the most recent release of smee-client (1.0.2) was [9 months ago](https://www.npmjs.com/package/smee-client).

@tcbyrd would you be able to cut a 1.0.3 release of smee-client? Also thanks for making such a handy little service :)

**Comment by tcbyrd** [comment]
@JasonEtco do you have access to that package? I have access to `smee-cli`, but not `smee-client`, so I can't publish it to the npm package everybody is using.

**Comment by JasonEtco** [comment]
I do - I'll go ahead and publish right now. I've also added you to it @tcbyrd.

**Comment by JasonEtco** [comment]
Done! Thanks all for your patience 🙏 Install now with `npm i smee-client@1.0.3` 🎉
