### ISSUE TITLE
Webhooks redelivered from the GitHub UI are not showing up

### ISSUE THREAD

**Issue by tarebyte** [probot/smee#72]
Hi there 👋 

We got an internal report that folks weren't able to resend GitHub App webhooks in GHE through the user interface.

After some investigation I think it's smee.io that may be having issue.

Below I've attached a GIF that includes me resending the same webhook (a push event) to both an ngrok listener and to smee.io

![webhooks](https://user-images.githubusercontent.com/564113/42770116-32e72ab0-88f2-11e8-9d95-e65d828a6a2f.gif)

It appears as though smee.io doesn't register if you send the same hook event a second time.

**Comment by JasonEtco** [comment]
Thanks @tarebyte - this is "intentional" but confusing. Smee ignores duplicate payloads that have the same event ID header, so that when it does its own "redeliver" feature that event doesn't show up twice in the UI.

However, when building this I didn't consider redelivering _from GitHub_. It'd be best to still show those duplicates if they've been redelivered from GitHub, not from Smee.

**Comment by JasonEtco** [comment]
Was able to reproduce ☝️ - in fact, `Clear deliveries` let me redeliver from GitHub again, so its definitely that front-end check. I'll try to fix this, but I won't have bandwidth until next week.
