### ISSUE TITLE
Proxying HTTP responses

### ISSUE THREAD

**Issue by bkeepers** [probot/smee#77]
Smee is currently a unidirectional channel for receiving POST requests and forwarding them to listening clients, ignoring the client's response.

There are a couple use cases where we'd like to figure out how to add support for true bi-directional proxying. For example, Slack's [events api](https://api.slack.com/events-api) depends on responses to know if webhooks were delivered successfully, and often allow responding with content that gets posted in Slack.

**Comment by JasonEtco** [comment]
We talked about this a bit during Probot Office Hours, so for posterity: this may require a rewrite of Smee, since [Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) specifically doesn't support bi-directional messages. In my mind this means WebSockets, but I'm all 👂s for another solution.
